# Generated by Django 5.2.8 on 2025-12-22 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_options_alter_rubric_options_alter_bb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('warranty_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Гарантия, мес')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='bboard.product', verbose_name='Профиль')),
            ],
        ),
    ]
